Repository 9oormthon-univ/2025_SEASONTHON_TEAM_73_BE, pull requests merged in 2025-09, with the labels that each got.

#13 [Feat/#12] 채팅 관련 기능 구현
  build.gradle
  src/main/java/com/season/livingmate/auth/controller/SignupController.java
  src/main/java/com/season/livingmate/auth/security/JwtProvider.java
  src/main/java/com/season/livingmate/auth/security/LoginFilter.java
  src/main/java/com/season/livingmate/chat/api/ChatController.java
  src/main/java/com/season/livingmate/chat/api/dto/request/ChatMessageReqDto.java
  src/main/java/com/season/livingmate/chat/api/dto/response/ChatMessageResDto.java
  src/main/java/com/season/livingmate/chat/api/dto/response/ChatRoomResDto.java
  src/main/java/com/season/livingmate/chat/application/ChatService.java
  src/main/java/com/season/livingmate/chat/domain/ChatRoom.java
  src/main/java/com/season/livingmate/chat/domain/ChatRoomStatus.java
  src/main/java/com/season/livingmate/chat/domain/Message.java
  src/main/java/com/season/livingmate/chat/domain/MessageType.java
  src/main/java/com/season/livingmate/chat/domain/WebSocketType.java
  src/main/java/com/season/livingmate/chat/domain/repository/ChatRoomRepository.java
  src/main/java/com/season/livingmate/chat/domain/repository/MessageRepository.java
  src/main/java/com/season/livingmate/chat/infra/JwtHandshakeInterceptor.java
  src/main/java/com/season/livingmate/chat/infra/WebSocketHandler.java
  src/main/java/com/season/livingmate/config/WebSocketConfig.java
  src/main/java/com/season/livingmate/exception/status/ErrorStatus.java
  src/main/java/com/season/livingmate/exception/status/SuccessStatus.java
  src/main/java/com/season/livingmate/global/entity/BaseEntity.java
  src/main/java/com/season/livingmate/post/domain/Post.java
  src/main/java/com/season/livingmate/user/api/dto/response/UserProfileResDto.java
  src/main/java/com/season/livingmate/user/domain/User.java
Labels: enhancement

#22 [MOD/#20] 게시글 생성, 수정 이미지 폼데이터로 수정
  src/main/java/com/season/livingmate/config/WebConfig.java
  src/main/java/com/season/livingmate/post/api/dto/PostController.java
  src/main/java/com/season/livingmate/post/api/dto/req/PostCreateReq.java
  src/main/java/com/season/livingmate/post/api/dto/req/PostUpdateReq.java
  src/main/java/com/season/livingmate/post/application/PostService.java
  src/main/resources/application.yml
Labels: mod

#25 [Mod/#20] front integration
  src/main/java/com/season/livingmate/map/api/dto/PostDetailMapRes.java
  src/main/java/com/season/livingmate/map/api/dto/PostMapDetailRes.java
  src/main/java/com/season/livingmate/map/api/dto/PostMapRes.java
  src/main/java/com/season/livingmate/post/api/dto/res/PostDetailRes.java
  src/main/java/com/season/livingmate/post/api/dto/res/PostListRes.java
  src/main/java/com/season/livingmate/post/domain/RoomType.java
Labels: mod

#26 [MERGE] Develop -> Main
  src/main/java/com/season/livingmate/map/api/dto/PostDetailMapRes.java
  src/main/java/com/season/livingmate/map/api/dto/PostMapDetailRes.java
  src/main/java/com/season/livingmate/map/api/dto/PostMapRes.java
  src/main/java/com/season/livingmate/post/api/dto/res/PostDetailRes.java
  src/main/java/com/season/livingmate/post/api/dto/res/PostListRes.java
  src/main/java/com/season/livingmate/post/domain/RoomType.java
  src/main/java/com/season/livingmate/user/api/dto/CertificateController.java
  src/main/java/com/season/livingmate/user/api/dto/UserController.java
  src/main/java/com/season/livingmate/user/api/dto/UserProfileController.java
  src/main/java/com/season/livingmate/user/api/dto/response/UserProfileResDto.java
  src/main/java/com/season/livingmate/user/api/dto/response/UserResDto.java
  src/main/java/com/season/livingmate/user/api/dto/resquest/UserProfileCreateReqDto.java
  src/main/java/com/season/livingmate/user/api/dto/resquest/UserProfileUpdateReqDto.java
  src/main/java/com/season/livingmate/user/application/CertificateService.java
  src/main/java/com/season/livingmate/user/application/UserService.java
  src/main/java/com/season/livingmate/user/domain/Certificate.java
  src/main/java/com/season/livingmate/user/domain/User.java
  src/main/java/com/season/livingmate/user/domain/UserProfile.java
  src/main/java/com/season/livingmate/user/entity/Gender.java
Labels: merge

#35 [MOD/#20] 게시글 생성 및 수정에 선호 성별 추가
  src/main/java/com/season/livingmate/post/api/dto/req/PostCreateReq.java
  src/main/java/com/season/livingmate/post/api/dto/req/PostUpdateReq.java
  src/main/java/com/season/livingmate/post/api/dto/res/PostDetailRes.java
  src/main/java/com/season/livingmate/post/api/dto/res/PostListRes.java
  src/main/java/com/season/livingmate/post/application/PostService.java
  src/main/java/com/season/livingmate/post/domain/Post.java
Labels: mod

#69 [Feat/#64] GPT 유저 추천 api 구현
  build.gradle
  src/main/java/com/season/livingmate/config/GptConfig.java
  src/main/java/com/season/livingmate/exception/status/ErrorStatus.java
  src/main/java/com/season/livingmate/gpt/api/UserRecommendationController.java
  src/main/java/com/season/livingmate/gpt/api/dto/request/GptRequest.java
  src/main/java/com/season/livingmate/gpt/api/dto/request/UserRecommendationReqDto.java
  src/main/java/com/season/livingmate/gpt/api/dto/response/GptResponse.java
  src/main/java/com/season/livingmate/gpt/api/dto/response/UserRecommendationResDto.java
  src/main/java/com/season/livingmate/gpt/application/GptService.java
  src/main/java/com/season/livingmate/gpt/application/UserRecommendationService.java
  src/main/java/com/season/livingmate/user/domain/repository/UserRepository.java
  src/main/resources/application.yml
Labels: enhancement

#74 [FEAT/#64] 추천 gpt 프롬포트 수정 추천 이유 세분화
  src/main/java/com/season/livingmate/gpt/application/GptService.java
  src/main/java/com/season/livingmate/gpt/application/UserRecommendationService.java
Labels: mod

#100 [MERGE/#20] develop -> main 머지
  src/main/java/com/season/livingmate/gpt/api/dto/response/UserRecommendationResDto.java
  src/main/java/com/season/livingmate/gpt/application/GptService.java
  src/main/java/com/season/livingmate/gpt/application/UserRecommendationService.java
Labels: merge
